### ISSUE TITLE
Senor Type 25 and 40 Support?

### ISSUE THREAD

**Issue by davidfungf** [ncd-io/NCDEnterpise-Python#1]
Does it support sensor type 25 & 40? We need the python library for time domain data retrieval on vibration sensor.

**Comment by io-Jacob** [comment]
Hi David,

We handled this through the corporate ticketing system and support was added in the branch: V2-Vibration-Mems. I'll merge this branch back into the main whenever I can go back through and test existing supported sensors as there were a couple sweeping changes to the COM layer.
